flags:
  mlu:
    paths:
    - xpu_graph/**/*mlu*/**
    - xpu_graph/**/*mlu*
    ignore:
    - xpu_graph/**/tests/**
    - xpu_graph/**/*test*
    - xpu_graph/**/*npu*/**
    - xpu_graph/**/*npu*
    - xpu_graph/**/*ascend*/**
    - xpu_graph/**/*ascend*
  npu:
    # paths:
    ignore:
    - xpu_graph/**/tests/**
    - xpu_graph/**/*test*
    - xpu_graph/**/*mlu*/**
    - xpu_graph/**/*mlu*
  # core:
  #   ignore:
  #   - xpu_graph/**/*mlu*/**
  #   - xpu_graph/**/*mlu*
  #   - xpu_graph/**/*npu*/**
  #   - xpu_graph/**/*npu*
  #   - xpu_graph/**/*ascend*/**
  #   - xpu_graph/**/*ascend*
  #   - xpu_graph/**/tests/**
  #   - xpu_graph/**/*test*

coverage:
  status:
    project:
      #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      # core:
      #   # basic
      #   target: auto #default
      #   threshold: 0%
      #   base: auto
      mlu:
        target: auto #default
        threshold: 0%
        base: auto
      npu:
        # basic
        target: auto #default
    patch:
      default:
        target: 80%
        threshold: 1%
comment:
  #this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: true # if true: only post the comment if coverage changes
  require_base: false # [true :: must have a base report to post]
  require_head: true # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]
