[[linter]]
code = 'BLACK'
include_patterns = ['**/*.py']
exclude_patterns = [
    '.git/**',
]
command = [
    'python3',
    'tools/linter/black_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python3',
    'tools/linter/pip_init.py',
    '--dry-run={{DRYRUN}}',
    'black==23.12.1',
]
