name: Request a feature
description: Request a feature in XPU_GRAPH
labels: [ "enhancement" ]

body:
- type: markdown
  attributes:
    value: |
      #### Disclaimer
      The core XPU_GRAPH team is small and has very limited capacity. We may not have time to look into your report.
      For the best results, please:
        - Avoid submitting duplicates. Search through [the existing and past issues](https://github.com/BD-Seed-HHW/xpu_graph/issues?q=is%3Aissue) first to see if it's been reported previously.
        - Check if the issue persists with a build from the latest source.
        - Provide all relevant information in the initial report, to prevent unnecessary back and forth discussion.
        - If you can, try to diagnose and/or fix the issue yourself. We welcome high quality contributions.
- type: textarea
  attributes:
    label: Describe the feature🚀
    description: |
      Please provide a clear and concise description of the feature proposal and outline the motivation for the proposal. Is your feature request related to a specific problem? e.g., *"I'm working on X and would like Y to be possible"*. If this is related to another GitHub issue, please link here too.

      If the code is too long (hopefully, it isn't), feel free to put it in a public gist and link it in the issue: https://gist.github.com.

    placeholder: |
      Please a clear and concise description of the feature proposal...

      ```python
      # Sample code to use the feature. (Optional)
      ```

      ```
      The feature should work as follows. (Optional)
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: References
    description: |
      Background or any other related issues or contents.

    placeholder: |
      Some Background or any other related issues or contents.
      [Some Docs](https://github.com/BD-Seed-HHW/xpu_graph/wiki)
      [Some Docs](https://github.com/BD-Seed-HHW/xpu_graph/wiki)
      [Some Docs](https://github.com/BD-Seed-HHW/xpu_graph/wiki)
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment details
    description: |
      Please include any relevant context about how you're running the reproducer e.g. which version of XPU_GRAPH, and what XPU you are using.
    placeholder: |
      PyTorch: ...
      NPU: ...
      MLU: ...
      XPU_GRAPH: ...
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
