name: Run test case on mlu
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
    paths_ignore:
      - 'xpu_graph/backend/ascend.py'
      - 'xpu_graph/backend/npu.py'
      - 'xpu_graph/passes/patterns/targets/ascend/'
      - 'xpu_graph/passes/patterns/targets/npu/'
      - 'tests/ascend'
      - 'tests/npu'
      - 'tests/ops'
      - 'docker/*'
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  run-tests:
    name: Run mlu tests
    runs-on: MLU
    steps:
      - uses: actions/checkout@v4
      - name: Running mlu tests
        shell: bash
        run: |
          echo "Running MLU tests..."
          docker run --rm --network=host --ipc=host --pid=host --privileged=true -v ${{ github.workspace }}:/opt/tiger/xpu_graph -u tiger -w /opt/tiger/xpu_graph hub.byted.org/ci/xpu_graph:205b8e9e4cac5da3f21e6fb5d804b924 python3 -m pytest --ignore=tests/xpu_ops --ignore=tests/ascend --ignore=tests/npu tests
