name: Run test case on mlu
on:
  pull_request:
    branches:
    - master
    types: [ opened, synchronize, reopened ]
    paths_ignore:
    - /docs/**
    - /doc/**
    - /README.md
    - /.github/ISSUE_TEMPLATE/**
  push:
    branches:
    - master
  workflow_dispatch:
env:
  XPU_GPRAH_PROXY: ${{ secrets.XPU_GPRAH_PROXY }}
defaults:
  run:
    shell: bash
jobs:
  run-tests:
    name: Run mlu tests
    runs-on: MLU
    container:
      image: hub.byted.org/ci/xpu_graph:934ebcfdd670bcea94aa0a0ed247a576
      options: --privileged=true --ipc=host --pid=host --user root --network host
    steps:
    - uses: actions/checkout@v4
    - name: Check updates
      id: update
      shell: bash
      run: |
        if [[ -n "$GITHUB_BASE_REF" ]]; then
          TARGET_REF="$GITHUB_BASE_REF"
        else
          TARGET_REF="master"
        fi
        git fetch origin $TARGET_REF
        ./scripts/check_updates_for_backends.sh origin/$TARGET_REF mlu || echo "updated=$?" >> $GITHUB_OUTPUT
    - name: Running mlu tests
      if: steps.update.outputs.updated == '1'
      shell: bash
      run: |
        export HTTP_PROXY=${XPU_GPRAH_PROXY} HTTPS_PROXY=${XPU_GPRAH_PROXY}
        pip install -e '.[dev]'
        echo "Running MLU tests..."
        python3 -m pytest --cov=xpu_graph tests/common tests/mlu
    - uses: codecov/codecov-action@v5
      if: steps.update.outputs.updated == '1' && success()
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        flags: mlu
        name: mlu-codecov
        use_pypi: true
        fail_ci_if_error: false
        verbose: true
