name: Run test suite
on:
  pull_request:
    branches:
      - master
    paths_ignore:
      - 'xpu_graph/backend/ascend.py'
      - 'xpu_graph/backend/npu.py'
      - 'xpu_graph/passes/patterns/targets/ascend/'
      - 'xpu_graph/passes/patterns/targets/npu/'
      - 'tests/ascend'
      - 'tests/npu'
      - 'tests/ops'
      - 'docker/*'
    types: [opened, synchronize, reopened]
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  run-tests:
    name: Run MLU tests
    runs-on: MLU
    steps:
      - uses: actions/checkout@v4
      - name: Running mlu tests
        shell: bash
        run: |
          echo "Running MLU tests..."
          python3 -m pytest --ignore=tests/xpu_ops --ignore=tests/ascend --ignore=tests/npu tests
