name: Run test suite
on: push
jobs:
  clone-code:
    runs-on: self-hosted
    steps:
      - name: clone xpu_graph code
        run: |
          rm -rf /data01/wangmingfa/mlu-ci
          mkdir -p /data01/wangmingfa/mlu-ci
          cd /data01/wangmingfa/mlu-ci
          git clone https://github.com/BD-Seed-HHW/xpu_graph.git
  run-tests:
    name: Run xpu_graph tests
    runs-on: self-hosted
    container:
      # image: hub.byted.org/tritonx/mlu-devel-ubuntu20.04:0.0.0
      image: cambricon-base/pytorch:v24.12.1-torch2.5.0-torchmlu1.24.1-debian10.11-py310
      # env:
      #     HTTP_PROXY: http://sys-proxy-rd-relay.byted.org:3128
      #     HTTPS_PROXY: http://sys-proxy-rd-relay.byted.org:3128
      # ports:
      #   - 5432:5432
      volumes:
        - /data01/wangmingfa/mlu-ci:/host
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /dev:/dev
        - /usr/bin/cnmon:/usr/bin/cnmon
      options: -e DISPLAY=$DISPLAY -e GDK_SCALE -e GDK_DPI_SCALE --privileged=true --ipc=host --pid=host 
    steps:
      - name: Running mlu tests
        run: |
          cd /host/xpu_graph
          ls -la
          pip install expecttest
          pip install -e .
          pip show xpu_graph
          python tests/mlu/test_*
          rm -rf /host/xpu_graph
          
