name: Run test suite
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  run-tests:
    name: Run xpu_graph tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Running mlu tests
        shell: bash
        run: |
          python3 -m venv --system-site-packages .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          echo "Running MLU tests..."
          python3 -m pytest --ignore=tests/xpu_ops tests
