name: ci
on:
  push:
    branches: [ push, pull_request ]
jobs:
  container-test-job:
    runs-on: self-hosted
    steps:
      - name: Check for dockerenv file
        uses: actions/checkout@v3
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        with:
          image: hub.byted.org/tritonx/mlu-devel-ubuntu20.04:0.0.0
          options: -v /data01/wangmingfa:/host
          run: (ls /host && echo Found dockerenv) || (echo No dockerenv)
