name: Run test suite
on: push
jobs:
  run-tests:
    name: Run xpu_graph tests
    runs-on: self-hosted
    container:
      image: hub.byted.org/tritonx/mlu-devel-ubuntu20.04:0.0.0
      volumes:
        - /data01/wangmingfa:/host
    steps:
      - name: Running xxx
        run: echo 'hello world'
