name: Run test suite
on: push
jobs:
  run-tests:
    name: Run xpu_graph tests
    runs-on: self-hosted
    container:
      image: hub.byted.org/tritonx/mlu-devel-ubuntu20.04:0.0.0
      volumes:
        - /data01/wangmingfa:/host
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /dev:/dev
        - /usr/bin/cnmon:/usr/bin/cnmon
      options: -e DISPLAY=$DISPLAY -e GDK_SCALE -e GDK_DPI_SCALE --privileged=true --ipc=host --pid=host 
    steps:
      - name: Running mlu tests
        run: source /opt/apps/venv/xpu-graph/bin/activate && pip install -e . && pytest tests/mlu/test_*
