name: DEMO workflow for mlu
on:
  pull_request:
    branches:
    - demo
    types: [ opened, synchronize, reopened ]
    paths-ignore:
    - 'README.md'
    - 'tests/*/**'
    - '!tests/common/**'
defaults:
  run:
    shell: bash
jobs:
  run-tests:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        shell: bash
        run: |
          echo "triggerd by changes"
