name: Run lint check
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  run-tests:
    name: Run Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Check
        shell: bash
        run: |
          PR_TITLE=pr_title.txt
          echo "${{ github.event.pull_request.title }}" > ${PR_TITLE}
          bash scripts/commit_msg_check.sh ${PR_TITLE}

          echo "fetching the HEAD of origin target branch."
          git fetch --depth=1 origin ${{ github.event.pull_request.base.ref }}
          bash scripts/lint_check.sh origin/${{ github.event.pull_request.base.ref }}
